In [5]:
import pandas as pd
import numpy as np

In [6]:
pd.__version__

'3.0.6'

In [7]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [8]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [15]:
df.head(20)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
5,2007,USA,Hybrid,Front-wheel drive,2,2290,6,266.0,4260,18.8,31.2
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
7,2005,USA,Gasoline,Front-wheel drive,4,2370,6,279.0,4090,17.4,30.2
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
9,2004,USA,Diesel,All-wheel drive,5,2330,6,280.0,4620,17.7,31.2
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
11,1996,Europe,Diesel,Front-wheel drive,4,2240,6,250.0,3980,16.7,31.4
12,1983,USA,Diesel,Front-wheel drive,3,2370,7,NaN,4390,20.7,30.4
13,2024,USA,Gasoline,Rear-wheel drive,4,2440,6,277.0,4790,20.2,30.2
14,2015,USA,Gasoline,Front-wheel drive,5,1900,6,202.0,4070,18.7,32.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
16,2021,Asia,Gasoline,All-wheel drive,5,2280,6,234.0,4750,20.1,29.7
17,2021,USA,Gasoline,Rear-wheel drive,5,2540,7,299.0,4690,17.9,30.2
18,1995,USA,Gasoline,Front-wheel drive,2,2490,6,264.0,4230,17.7,28.5
19,2006,USA,Gasoline,All-wheel drive,4,2320,6,251.0,4410,15.8,31.4

In [16]:
df.tail(20)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
9980,1977,USA,Hybrid,Front-wheel drive,5,2390,6,NaN,4550,19.8,32.0
9981,2018,Europe,Diesel,All-wheel drive,4,2530,7,283.0,4670,19.7,33.8
9982,2014,Europe,Gasoline,Front-wheel drive,5,2100,6,223.0,4270,NaN,34.0
9983,2017,Europe,Gasoline,Rear-wheel drive,2,2410,7,278.0,4370,NaN,31.3
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9985,2024,USA,Gasoline,Front-wheel drive,3,2170,6,246.0,3890,17.1,33.7
9986,1984,Europe,Gasoline,Front-wheel drive,3,2330,6,NaN,4110,19.2,29.6
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9988,2016,USA,Hybrid,Rear-wheel drive,2,2340,7,273.0,4400,18.6,30.8
9989,1986,Europe,Diesel,Front-wheel drive,3,2410,6,277.0,4160,20.2,30.7
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9991,1987,USA,Gasoline,Rear-wheel drive,4,2130,5,228.0,4040,17.2,26.3
9992,2000,Europe,Gasoline,Front-wheel drive,3,2470,7,271.0,3990,17.3,28.1
9993,2007,USA,Diesel,Rear-wheel drive,2,1950,6,234.0,4250,19.9,30.7
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [9]:
total_counts = len(df) 
print(total_counts)

10000

In [11]:
fuel_types_count = df["fuel_type"].nunique()
print(fuel_types_count)

3

In [17]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [23]:
max_efficiency = df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()
print(max_efficiency)

41.2

In [28]:
first_median = df["horsepower"].median()
print(first_median)

254.0

In [33]:
most_frequent_value = df["horsepower"].mode()[0]
print(most_frequent_value)

252.0

In [34]:
df["horsepower"] = df["horsepower"].fillna(most_frequent_value)

In [37]:
final_median = df["horsepower"].median()
print(final_median)

252.0

In [44]:
df_asia = df[df["origin"] == "Asia"]
X = df_asia[["vehicle_weight", "model_year"]].head(7).to_numpy()
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

In [49]:
XTX = X.T@X
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]

In [50]:
inverted_XTX = np.linalg.inv(XTX)
print(inverted_XTX)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [51]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print(y)

[1100 1300  800  900 1000 1100 1200]

In [52]:
w = inverted_XTX @ X.T @ y
print(w)

[0.13644777 0.2327492 ]

In [54]:
sum_result = w.sum()
print(sum_result)

0.36919696904925486